### ISSUE TITLE
Blank canva laggy then crash (gradio: 3.23.0)

### ISSUE THREAD

**Issue by pralium444** [opparco/stable-diffusion-webui-two-shot#38]
Creating Blank canva then hover on to it
With updated Automatic1111 -> (python 3.10.9)  (gradio: 3.23.0)
needs updating to 3.23 ? "extensions" folder show gradio-3.16.2-py3-none-any.whl
Any help appreciated. Thanks for your extension ! much love

**Comment by mazejk** [comment]
same issue here, did you fix it ?

**Comment by pralium444** [comment]
even divisions in rectangular tab not working, latest update from today didn't fix the issue

**Comment by MrZomboED** [comment]
same shit man, even old version lags

**Comment by MrZomboED** [comment]
Could sound stupid but i fixed it just with changing browser. It's been laggy in operagx, but all perfectly work in edge 

Edit. Won't work in other browsers anymore

**Comment by JonathanWac** [comment]
Just wanted to confirm also. I had the same issue and it fixed itself by moving from Chrome to Edge. I can now draw and use the canvas just fine.

**Comment by mazejk** [comment]
changing browser doesn't work for me unfortunately

**Comment by pralium444** [comment]
same, does not work even Ashen's fork.
I'm on chrome, i tried every browser...

**Comment by cubertarray** [comment]
Problem persists after fresh install of both WebUI and two-shot extension.

But I also noticed, that problem with freshly created blank canvas only persists on the text2img tab. When I use the two-shot extension to create blank canvas on img2img tab, I can draw on it without any problems. 

Maybe since img2img tab has gradio-based drawing tools by default, it forces two-shot extension to use the main (3.23.0 for me currently) version of gradio, while txt2img doesn't?

Edit: After some time without any particular meaningful steps problem appeared on img2img tab too. Looks like its capable of working initially, but breaks on repetition.

**Comment by AsheGeisha** [comment]
Anyone found the solution?

**Comment by Kelebrim** [comment]
Found a workaround, at least for me, created white png of required size in paint and uploaded it instead of creating blank canvas

**Comment by Meathelix1** [comment]
Still have this issue today. Anyone found a fix?

**Comment by pralium444** [comment]
Creating a 512x512 image with photoshop, then importing and redraw on it works
EDIT : the canva does not crash but the separation AND does not work, it blends the two characters

**Comment by MrZomboED** [comment]
Guys, I figured out what the problem is. Page scaling. Don't change it, leave it at 100%. The problem happens even if you give a value of 110%. After I returned the usual 100%, the canvas worked for me even where it had refused to work before
For some reason nothing crashes if i doing 90% and less values, but crashes if scaling is more than 100%

**Comment by pralium444** [comment]
for me at 100%, doesn't crash but can't draw anything

**Comment by evanerichards** [comment]
I've just found this thread. I'm running into the same thing. My page scaling is at 100% so that isn't my issue.

**Comment by Muskworker** [comment]
My page scaling was at 100% in the browser but I still had the alert show that I was at 200%.

Setting my scaling to 50% let it run.
